version: '3.9'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=secretRootPasswd
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "33306:80"
    environment:
      - MYSQL_ROOT_PASSWORD=secretRootPasswd
      - PMA_HOST=mysql
    profiles:
      - debug
    depends_on:
      - mysql
  laramix:
    image: node:14.15-alpine3.13
    command: [ "npm", "run-script", "docker-install" ]
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
    profiles:
      - dev
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      target: php_laravel
    command: ["apache2-foreground"]
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    volumes:
      - ./:/var/www/php
    depends_on:
      - mysql
