version: '3.9'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=secretRootPasswd
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - backend
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=error
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    depends_on:
      - mysql
    restart: always
    networks:
      - backend
      - frontend
  proxy:
    image: dimmaryanto93/laravel-proxy:latest
    ports:
      - "80:80"
    build:
      context: .docker
      dockerfile: Dockerfile-nginx
      args:
        NGINX_CONF_TEMPLATE: default.template.conf
    environment:
      APPLICATION_PORT: 80
      BACKEND_HOST: laravel
      BACKEND_PORT: 80
      BACKEND_CONTEXT_PATH: /
    depends_on:
      - laravel
    networks:
      - frontend
networks:
  frontend:
  backend:
