version: '3.9'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=secretRootPasswd
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - backend

  laravel:
    image: dimmaryanto93/udemy-laravel-app:https-latest
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Dockerfile-ssl
    environment:
      - APP_ENV=production
      - APACHE_SERVER_NAME=udemy.dimas-maryanto.com
      - SSL_CERTIFICATE_FILE=docker_pemula_sampai_mahir.crt
      - SSL_CERTIFICATE_KEY_FILE=docker_pemula_sampai_mahir.key
      - APP_DEBUG=false
      - LOG_LEVEL=error
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    depends_on:
      - mysql
    restart: always
    networks:
      - backend
    volumes:
      - type: bind
        source: .docker/ssl/certs/docker_pemula_sampai_mahir.crt
        target: /etc/ssl/certs/docker_pemula_sampai_mahir.crt
      - type: bind
        source: .docker/ssl/key/docker_pemula_sampai_mahir.key
        target: /etc/ssl/private/docker_pemula_sampai_mahir.key
networks:
  backend:
